### ISSUE TITLE
updatesForPatch throws when adding multiple items to end of array with -

### ISSUE THREAD

**Issue by chrisrichard** [mrcranky/rfc6902-mongodb#1]
Calling updatesForPatch with mutiple patches that append to the end of an array with e.g. `/path/to/array/-` throws error:  "TypeError: i.items is not iterable"

Executing the following on codepen.io demonstrates the issue:

```
import {updatesForPatch} from "https://esm.sh/rfc6902-mongodb";

const patches = [
      {
        op: 'add',
        path: '/journey/inquiries/-',
        value: { type: 'test-2' }
      },
      {
        op: 'add',
        path: '/journey/inquiries/-',
        value: { type: 'test-3' }
      }
];

const document = {
      id: '6fd15dd7-bf03-402e-b469-6ffcc7feb333',
      journey: { inquiries: [ 
        { type: 'test-0' },
        { type: 'test-1' }
      ] },
};

console.log(updatesForPatch(patches, document))
```

**Comment by chrisrichard** [comment]
Seems to work better for my scenarios if I make the following change:

```
function isAppend(pushUpdate) {
    if (typeof(pushUpdate) === 'object') {
        if (pushUpdate.$position !==  undefined) {
            return { append: false, items: pushUpdate.$each };
        } else {
            return { append: true, items: [pushUpdate] };  // changed from items: pushUpdate.$each
        }
    } else {
        return { append: true, items: [pushUpdate] };
    }
}
~``

**Comment by mrcranky** [comment]
That's a great spot, thanks, but the fix is not quite right. The update coalescing code is seeing the append of a value which is an object and interpreting it as a MongoDB operation, even though it doesn't have the correct $each field. Your change would make it work for object appends, but it would break for non-object appends. But the real fix is very close to that, going to push it up with associated new unit test and make a release 0.1.3 with the fix.
